<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Plant Care Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
        }

        h1,
        h2 {
            margin-bottom: 5px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th,
        td {
            border: 1px solid #000;
            padding: 6px;
        }

        th {
            background: #f0f0f0;
        }
    </style>
</head>

<body>

    <h1>Plant Care Report</h1>

    <p>
        <strong>Plant Name:</strong> {{ $product->product_name }}<br>
        <strong>Seller:</strong> {{ $seller->business_name }}<br>
        <strong>Generated On:</strong> {{ now()->format('d M Y') }}
    </p>

    <hr>

    <h2>Latest Growth Status</h2>
    @if($latestGrowth)
        <p>
            Stage: {{ ucfirst($latestGrowth->growth_stage) }}<br>
            Height: {{ $latestGrowth->height_cm ?? '-' }} cm<br>
            Notes: {{ $latestGrowth->notes ?? '-' }}
        </p>
    @else
        <p>No growth data recorded.</p>
    @endif

    <hr>

    <h2>Growth History</h2>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Stage</th>
                <th>Height (cm)</th>
                <th>Notes</th>
            </tr>
        </thead>
        <tbody>
            @forelse($growthLogs as $log)
                <tr>
                    <td>{{ $log->created_at->format('d M Y') }}</td>
                    <td>{{ ucfirst($log->growth_stage) }}</td>
                    <td>{{ $log->height_cm ?? '-' }}</td>
                    <td>{{ $log->notes ?? '-' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4">No growth records</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <hr>

    <h2>Care History</h2>
    <table>
        <thead>
            <tr>
                <th>Care Date</th>
                <th>Care Type</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            @forelse($careLogs as $log)
                <tr>
                    <td>{{ \Carbon\Carbon::parse($log->care_date)->format('d M Y') }}</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $log->care_type)) }}</td>
                    <td>{{ $log->description ?? '-' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="3">No care records</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <p style="margin-top:30px;">
        <em>This report was generated by the Aether & Leaf.Co.</em>
    </p>

</body>

</html>